git add "SilentPatchVC.asi"
git add "SilentPatchVC.ini"
git add "data\maps\club\CLUB.ipl"
git add "data\maps\hotel\hotel.IPL"
git add "data\maps\littleha\littleha.ipl"
git add "data\maps\mansion\mansion.ipl"
git add "data\maps\oceandn\oceandN.ipl"
git add "data\maps\oceandrv\oceandrv.ipl"
git add "data\maps\stripclb\stripclb.ipl"
git add "data\maps\washints\washints.ipl"
git add "GInputAPI (for modders)\GInputAPI.h"
git add "GInputAPI (for modders)\ReadMe.txt"
git add "GInputVC.asi"
git add "GInputVC.ini"
git add "docs\GAME CONTROLS FULL LIST.txt"
git add "docs\cheat_list_ps3.html"
git add "docs\cheat_list_xbox.html"
git add "models\ps3btns.txd"
git add "models\sixaxis.txd"
git add "models\x360btns.txd"
git add "git-command.bat"